### ISSUE TITLE
libFreeImage.dylib has no arm options MAC

### ISSUE THREAD

**Issue by a-727** [MonoGame/MonoGame.Dependencies#165]
I'm trying to code a MonoGame project on mac. I got this failure, with a bunch of folders it checked. 
<img width="1082" alt="MonoGame Texture Importer failure" src="https://github.com/MonoGame/MonoGame.Dependencies/assets/145040318/fd7d5047-1839-4251-bb7b-d560c9aca657">
It *looks* like none of them exist. So I build my last MonoGame game without textures. That was actually a smart choice because that game was build on pixels. I can't do that for this game, though.

But actually, ONE does exist. For ONE file, I got this error:
`'/Users/grantsd/.nuget/packages/dotnet-mgcb/3.8.1.303/tools/net6.0/any/libFreeImage.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64'))`
There's no arm64 freeImage found in this library for mac. Could someone add it?

**Comment by a-727** [comment]
I

**Comment by mrhelmut** [comment]
This is already addressed with a new dedicated repo but not yet plugged into the public release: https://github.com/MonoGame/MonoGame.Library.FreeImage

If need be, you can grab the dylib there.
